# Generated by Django 5.1 on 2025-02-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('PIX', 'PIX')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], max_length=5),
        ),
    ]
