# Generated by Django 5.1 on 2025-01-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='valor',
            new_name='valorMensalidade',
        ),
    ]
