# Generated by Django 5.1 on 2025-02-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mensalidade_forma_pagamento_alter_turma_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='valorMensalidade',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Mensalidade'),
        ),
    ]
