# Generated by Django 5.1 on 2025-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_valor_turma_valormensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
