# Generated by Django 5.1 on 2025-02-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mensalidade_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
