# Generated by Django 5.1 on 2025-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mensalidade_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
