# Generated by Django 5.1 on 2025-02-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mensalidade_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Matrícula'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')]),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Em Atraso', 'Em Atraso')], default='Em Aberto', max_length=20),
        ),
    ]
