# Generated by Django 5.1 on 2025-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mensalidade_mes_alter_mensalidade_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidade',
            name='data_vencimento',
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Em Atraso', 'Em Atraso')], max_length=20),
        ),
    ]
