# Generated by Django 5.1 on 2025-02-07 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_mensalidade_data_vencimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidade',
            name='dia_pagamento',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='mes',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Em Atraso', 'Em Atraso')], default='Em Aberto', max_length=20),
        ),
    ]
