# Generated by Django 5.1 on 2025-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_mensalidade_dia_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='valorMatricula',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
            preserve_default=False,
        ),
    ]
