# Generated by Django 5.1 on 2025-02-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_turma_valormatricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(max_length=100, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='valorMatricula',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='valorMensalidade',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Mensalidade'),
        ),
    ]
