# Generated by Django 5.1 on 2025-02-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_mensalidade_desconto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidade',
            old_name='valor',
            new_name='valor_final',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='desconto_aplicado',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
