# Generated by Django 5.1 on 2025-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome_escola',
        ),
        migrations.AddField(
            model_name='perfil',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
