# Generated by Django 5.1 on 2025-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_perfil_nome_escola_perfil_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='certificado',
        ),
        migrations.AddField(
            model_name='perfil',
            name='certificado_homologacao',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='certificado_producao',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
