# Generated by Django 5.1 on 2025-02-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_perfil_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_escola',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
