# Generated by Django 5.1 on 2025-02-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_perfil_nome_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
