# Generated by Django 5.1 on 2025-02-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_aluno_cpf_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='certificado_homologacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='certificado_producao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='client_secret',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável'),
        ),
    ]
