# Generated by Django 5.1 on 2025-02-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_perfil_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
