# Generated by Django 5.1 on 2025-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_perfil_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Telefone')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
            ],
        ),
    ]
